# Learn more about services, parameters and containers at
# https://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

services:
   encoder.password:
        class: WikiBundle\Encoder\EncoderPassword
        arguments: 
            - '@security.password_encoder'
           
   mailer.contact_mailer:
        class: WikiBundle\Mailer\ContactMailer
        arguments: 
            - '%kernel.root_dir%'
            - '@templating'
            - '@mailer'
            - '%mailer_from_email%'
            - '%mailer_to_email%'