# Learn more about services, parameters and containers at
# https://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

services:
   encoder.password:
       class: WikiBundle\Encoder\EncoderPassword
       arguments: 
           - '@security.password_encoder'
